# GOLANG
# input test
gd:
	go run a.go i1.txt
# sample test
gs:
	go run a.go i1.txt
# input test part 2
gd2:
	go run b.go i1.txt
# sample test part 2
gs2:
	go run b.go i2.txt

# PYTHON
d:
	python3 a.py i1.txt
s:
	python3 a.py i2.txt
d2:
	python3 b.py i1.txt
s2:
	python3 b.py i2.txt

